### ISSUE TITLE
When generating a view, it always replace the stylesheet

### ISSUE THREAD

**Issue by baldrailers** [revans/Ti#1]

**Comment by rupakg** [comment]
Can you explain what you expect it should do and what is the behavior now?

**Comment by baldrailers** [comment]
the current behavior is that when you generate a view 

`ti s window Settings main`

This will generate a template stylesheet located in `app/<app_name/stylesheets/_settings.sass`

When you have updates to that file, say you already have modifications and you generate another view under Settings

`ti s window Settings details`

This will replace the sass in the `app/<app_name>/stylesheets/_settings.sass` using the default template that `ti` provides.

We need to be able to detect if the file already exists and then ask the user if they want to replace it or not.

**Comment by revans** [comment]
I'd have to look, but I think Rails 3.1 is going to be creating an individual sass/coffee file for each view. If so, that is something that we might to do as well. e.g. 

`ti s window Settings main #=> app/::app_name::/stylesheets/settings/main.sass`

`ti s window Settings details #=> app/::app_name::/stylesheets/settings/details.sass`

**Comment by baldrailers** [comment]
Actually if we adapt what Robert is saying, that will be faster to implement, the next question is that, do we really limit the folder creation into that part like:

`app/::app_name::/stylesheets/settings/main.sass` and `app/::app_name::/stylesheets/settings/details.sass`

what if a user wants to have another view under `settings/details`

**Comment by revans** [comment]
I'm trying to think through a reason why someone would choose to do:

`app/::app_name::/stylesheets/settings/details.sass`
`app/::app_name::/stylesheets/settings/details/main.sass`

instead of something like:

`app/::app_name::/stylesheets/settings/details/index.sass`
`app/::app_name::/stylesheets/settings/details/main.sass`

I think if we supported the former, we'd be encouraging bad design. Thoughts?

**Comment by baldrailers** [comment]
I think the idea is to have every views on their own sass file, but if it's already member of a domain, it should stick there?

The current implementation:

`app/::app_name::/stylesheets/_settings.sass`

**Comment by baldrailers** [comment]
I think we can close this 98c3906
