### ISSUE TITLE
SASS Compiler 

### ISSUE THREAD

**Issue by baldrailers** [revans/Ti#11]
SASS Compiler should be implemented just like CoffeeCompiler. I think the idea is to have sprocket in place right?

**Comment by revans** [comment]
I'm not yet sure how much of a benefit sprockets would provide.

**Comment by baldrailers** [comment]
This is done: https://github.com/codewranglers/Ti/commit/ba88674320f2ff4bb517b8f1db3d8b3ffc1c5d7a 

Kindly verify. I think the next move is to have the `sass compile` without calling `system`
