### ISSUE TITLE
Ti Build

### ISSUE THREAD

**Issue by revans** [revans/Ti#13]
The building of the iphone app should all be part of Ti core.

**Comment by baldrailers** [comment]
This is done, kindly verify: https://github.com/codewranglers/Ti/commit/ba88674320f2ff4bb517b8f1db3d8b3ffc1c5d7a

You can build and compile sass and coffee using `ti`:

`ti compile all`  <- compiles all including sass and coffee

`ti compile sass`
`ti compile coffee`

`ti build iphone` <- Build by platform. This is the same implementation as `rake build:iphone`
